### ISSUE TITLE
Unexpected token ] in JSON at position 346

### ISSUE THREAD

**Issue by tjmcdonough** [total-typescript/react-typescript-tutorial#7]
I am getting the following error when trying to run `npm run exercise 01`. Any ideas why?

```
PS C:\Projects\react-typescript-tutorial> npm run exercise 01

> react-typescript-tutorial@1.0.0 exercise
> tt-cli run 01

undefined:16
  ]
  ^

SyntaxError: Unexpected token ] in JSON at position 346
    at JSON.parse (<anonymous>)
    at runExercise (C:\Projects\react-typescript-tutorial\node_modules\@total-typescript\exercise-cli\dist\bin.js:55:25)
    at Command.<anonymous> (C:\Projects\react-typescript-tutorial\node_modules\@total-typescript\exercise-cli\dist\bin.js:140:26)
    at Command.listener [as _actionHandler] (C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:482:17)
    at C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1283:65
    at Command._chainOrCall (C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1177:12)
    at Command._parseCommand (C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1283:27)
    at C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1081:27
    at Command._chainOrCall (C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1177:12)
    at Command._dispatchSubcommand (C:\Projects\react-typescript-tutorial\node_modules\commander\lib\command.js:1077:23)

Node.js v18.16.0
```

**Comment by mattpocock** [comment]
Is this still happening? I think I made some changes upstream that fix this bug. Closing pre-emptively.
